-- AlterTable
ALTER TABLE "ApiKey" ADD COLUMN     "allowedOrigins" TEXT NOT NULL DEFAULT '*',
ADD COLUMN     "dailyLimit" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "lastRequestDate" TIMESTAMP(3),
ADD COLUMN     "monthlyLimit" INTEGER NOT NULL DEFAULT 30000,
ADD COLUMN     "planType" TEXT NOT NULL DEFAULT 'free',
ADD COLUMN     "rateLimitCount" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "rateLimitWindow" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "requestsThisMonth" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "requestsToday" INTEGER NOT NULL DEFAULT 0;
